    - name: create target group
      elb_target_group:
        name: ansible-app
        region: "{{region}}"
        protocol: http
        port: 5000
        vpc_id: vpc-5a406b32
        health_check_path: /
        state: present
    - name: register targets
      elb_target:
        target_group_name: ansible-app
        region: "{{region}}"
        target_id: "{{item['instance_id']}}"
        state: present
      with_items:
        - "{{ ec2targets['instances'] }}"
